package entidades;
// Generated 11-oct-2018 9:50:02 by Hibernate Tools 5.2.10.Final

/**
 * Contactos generated by hbm2java
 */
public class Contactos implements java.io.Serializable {

	private int idContacto;
	private String nombre;
	private String email;
	private int edad;

	public Contactos() {
	}

	public Contactos(int idContacto, String nombre, int edad) {
		this.idContacto = idContacto;
		this.nombre = nombre;
		this.edad = edad;
	}

	public Contactos(int idContacto, String nombre, String email, int edad) {
		this.idContacto = idContacto;
		this.nombre = nombre;
		this.email = email;
		this.edad = edad;
	}

	public int getIdContacto() {
		return this.idContacto;
	}

	public void setIdContacto(int idContacto) {
		this.idContacto = idContacto;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public int getEdad() {
		return this.edad;
	}

	public void setEdad(int edad) {
		this.edad = edad;
	}

}
